apiVersion: v1
kind: Service
metadata:
  labels:
    app: stop-watch
  name: stop-watch-svc
spec:
  type: NodePort
  ports:
  - name: "stop-watch-svc"
    port: 3500
    targetPort: 3500
    nodePort: 31011
  selector:
    app: stop-watch
    