apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-error1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-error1
  template:
    metadata:
      labels:
        app: webapp-error1
    spec:
      containers:
        - name: webapp-error1
          image: kennytoro/errormsg
          ports:
            - containerPort: 8080
